# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/java/
language: java

jdk:
  - oraclejdk8
  
#Maven local cache
cache:
  directories:
      - "${HOME}/.m2"

notifications:
  email: false